version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/Movix

hooks:
  AfterInstall:
    - runas: root
      timeout: 60
      command: chmod +x scripts/start_pm2.sh
      location: scripts/start_pm2.sh

